version: "3.7"
services:
    webserver:
        image: webserver
        build:
            context: ./webserver
            dockerfile: Dockerfile
        hostname: webserver
        ports:
            - "8080:8080"
        container_name: webserver
        links:
            - database
        depends_on:
            - database
    database:
        image: database
        build:
            context: ./database
            dockerfile: Dockerfile
        hostname: database
        ports:
            - "8081:3307"
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: 0.0.0.0
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: db
        volumes:
            - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
