version: "3.7"
services:
    webserver:
        image: webserver
        build:
            context: ./webserver
            dockerfile: Dockerfile
        hostname: webserver
        ports:
            - "80:80"
        container_name: webserver
