DROP DATABASE IF EXISTS db;
CREATE DATABASE db;
USE db;

DROP TABLE IF EXISTS users;
CREATE TABLE users(
	UserID INTEGER NOT NULL AUTO_INCREMENT,
	Username VARCHAR(30) NOT NULL,
	Password VARCHAR(128) NOT NULL,
	TotalVids INTEGER,
	DateCreated DATE,
	Email VARCHAR(50),
	CONSTRAINT users_pk PRIMARY KEY(UserID)
);

DROP TABLE IF EXISTS videos;
CREATE TABLE videos(
	VideoID INTEGER NOT NULL AUTO_INCREMENT,
	UserID INTEGER NOT NULL,
	VideoUser VARCHAR(30) NOT NULL,
	VideoTitle VARCHAR(100),
	VideoURL VARCHAR(2000),
	DateUploaded DATE,
	CONSTRAINT Video_pk PRIMARY KEY(VideoID),
	CONSTRAINT Video_fk FOREIGN KEY (UserID) 
		REFERENCES users(UserID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

